import { DEFAULT_BUCKET_ID, type Place } from './types';

const now = Date.now();
const t = (daysAgo: number) => now - daysAgo * 86_400_000;

const base = (id: string, createdDaysAgo: number) => ({
  id,
  bucketIds: [DEFAULT_BUCKET_ID],
  createdAt: t(createdDaysAgo),
  updatedAt: t(createdDaysAgo),
});

// Photos: Unsplash — stable, license-free, no auth required.
export const SEED_PLACES: Place[] = [
  {
    ...base('p-lisboa-1', 28),
    title: 'A Cevicheria',
    category: 'Eat',
    city: 'Lisbon',
    country: 'Portugal',
    coordinates: { latitude: 38.7156, longitude: -9.1528 },
    sourceUrl: 'https://www.instagram.com/acevicheria_lisboa/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=1400&q=80',
    notes: 'Chef Kiko’s Peruvian spot in Príncipe Real. No reservations — show up at 6.',
    tags: ['peruvian', 'ceviche', 'dinner', 'natural-wine'],
  },
  {
    ...base('p-lisboa-2', 22),
    title: 'Santa Clara 1728',
    category: 'Stay',
    city: 'Lisbon',
    country: 'Portugal',
    coordinates: { latitude: 38.7148, longitude: -9.1244 },
    sourceUrl: 'https://www.santaclara1728.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1400&q=80',
    notes: 'Six rooms overlooking the flea market. Linen everything.',
    tags: ['boutique', 'alfama', 'quiet'],
  },
  {
    ...base('p-mexico-1', 19),
    title: 'Contramar',
    category: 'Eat',
    city: 'Mexico City',
    country: 'Mexico',
    coordinates: { latitude: 19.4147, longitude: -99.1712 },
    sourceUrl: 'https://contramar.com.mx',
    thumbnailUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1400&q=80',
    notes: 'Long lunch. Tuna tostadas, pescado a la talla, a lot of wine.',
    tags: ['seafood', 'lunch', 'roma-norte', 'iconic'],
  },
  {
    ...base('p-mexico-2', 14),
    title: 'Casa Luis Barragán',
    category: 'See',
    city: 'Mexico City',
    country: 'Mexico',
    coordinates: { latitude: 19.4113, longitude: -99.1923 },
    sourceUrl: 'https://casaluisbarragan.org',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=80',
    notes: 'Book weeks ahead. Morning slot for the light on the pink wall.',
    tags: ['architecture', 'museum', 'morning'],
  },
  {
    ...base('p-kyoto-1', 11),
    title: 'Shōren-in at dusk',
    category: 'See',
    city: 'Kyoto',
    country: 'Japan',
    coordinates: { latitude: 35.006, longitude: 135.7819 },
    sourceUrl: 'https://www.shorenin.com/english/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1400&q=80',
    notes: 'Illuminated evening openings in spring and autumn. Quiet. Very.',
    tags: ['temple', 'evening', 'garden', 'autumn'],
  },
  {
    ...base('p-kyoto-2', 9),
    title: 'Kissa Madragoa',
    category: 'Eat',
    city: 'Kyoto',
    country: 'Japan',
    sourceUrl: 'https://www.instagram.com/kissa_madragoa/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=1400&q=80',
    notes: 'Kissaten-style cafe. Cream soda, thick toast, jazz records.',
    tags: ['cafe', 'kissaten', 'coffee'],
  },
  {
    ...base('p-lagos-1', 6),
    title: 'Nok by Alara',
    category: 'Eat',
    city: 'Lagos',
    country: 'Nigeria',
    coordinates: { latitude: 6.4405, longitude: 3.4624 },
    sourceUrl: 'https://www.instagram.com/nokbyalara/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=1400&q=80',
    notes: 'Pan-African tasting menu. Ask for the jollof arancini.',
    tags: ['pan-african', 'dinner', 'victoria-island'],
  },
  {
    ...base('p-copenhagen-1', 3),
    title: 'Apollo Bar',
    category: 'Eat',
    city: 'Copenhagen',
    country: 'Denmark',
    coordinates: { latitude: 55.6886, longitude: 12.5772 },
    sourceUrl: 'https://apollobar.dk',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1400&q=80',
    notes: 'Lunch in the courtyard of the old art academy. Natural wine, long bread.',
    tags: ['natural-wine', 'lunch', 'courtyard'],
  },
];

// Candidate pool for the suggestions engine — places the user hasn't saved
// yet, seeded so the Suggestions tab isn't empty on first launch.
// When an LLM backend is plugged in, this pool becomes the retrieval corpus.
export const CANDIDATE_PLACES: Place[] = [
  {
    ...base('c-lisboa-1', 0),
    title: 'Prado',
    category: 'Eat',
    city: 'Lisbon',
    country: 'Portugal',
    coordinates: { latitude: 38.7118, longitude: -9.1336 },
    sourceUrl: 'https://pradorestaurante.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=1400&q=80',
    notes: 'Farm-to-table in a tiled hall near Alfama. Natural wine list two miles long.',
    tags: ['natural-wine', 'lunch', 'alfama'],
  },
  {
    ...base('c-lisboa-2', 0),
    title: 'Palácio Belmonte',
    category: 'Stay',
    city: 'Lisbon',
    country: 'Portugal',
    sourceUrl: 'https://www.palaciobelmonte.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551776235-dde6d482980b?w=1400&q=80',
    notes: 'Ten suites inside a 15th-century palace above the castle.',
    tags: ['boutique', 'alfama', 'quiet', 'historic'],
  },
  {
    ...base('c-mexico-1', 0),
    title: 'Rosetta',
    category: 'Eat',
    city: 'Mexico City',
    country: 'Mexico',
    sourceUrl: 'https://rosetta.com.mx',
    thumbnailUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1400&q=80',
    notes: 'Elena Reygadas. Sit upstairs. Order the ravioli de flor de calabaza.',
    tags: ['italian-mx', 'roma-norte', 'dinner'],
  },
  {
    ...base('c-mexico-2', 0),
    title: 'Museo Jumex',
    category: 'See',
    city: 'Mexico City',
    country: 'Mexico',
    sourceUrl: 'https://www.fundacionjumex.org',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1400&q=80',
    notes: 'David Chipperfield building. Rotating contemporary shows. Free Sundays.',
    tags: ['museum', 'architecture', 'contemporary'],
  },
  {
    ...base('c-kyoto-1', 0),
    title: 'Hosoo Gallery',
    category: 'See',
    city: 'Kyoto',
    country: 'Japan',
    sourceUrl: 'https://www.hosoogallery.jp',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1400&q=80',
    notes: '300-year-old Nishijin textile house, now a design gallery.',
    tags: ['design', 'textile', 'gallery'],
  },
  {
    ...base('c-kyoto-2', 0),
    title: 'Hotel Shinmonzen',
    category: 'Stay',
    city: 'Kyoto',
    country: 'Japan',
    sourceUrl: 'https://www.hotelshinmonzen.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1400&q=80',
    notes: 'Tadao Ando + Rémi Tessier. Nine rooms on the Shirakawa canal.',
    tags: ['boutique', 'architecture', 'quiet'],
  },
  {
    ...base('c-copenhagen-1', 0),
    title: 'Designmuseum Danmark',
    category: 'See',
    city: 'Copenhagen',
    country: 'Denmark',
    sourceUrl: 'https://designmuseum.dk',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551038247-3d9af20df552?w=1400&q=80',
    notes: 'The chair hall alone. Go on a grey morning.',
    tags: ['museum', 'design', 'morning'],
  },
  {
    ...base('c-copenhagen-2', 0),
    title: 'Hotel Sanders',
    category: 'Stay',
    city: 'Copenhagen',
    country: 'Denmark',
    sourceUrl: 'https://hotelsanders.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1400&q=80',
    notes: 'Rooftop bar, rattan everywhere, old Royal Theatre neighbourhood.',
    tags: ['boutique', 'rooftop', 'quiet'],
  },
  {
    ...base('c-lagos-1', 0),
    title: 'Terra Kulture',
    category: 'See',
    city: 'Lagos',
    country: 'Nigeria',
    sourceUrl: 'https://www.terrakulture.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1533757704860-2a279ba77c82?w=1400&q=80',
    notes: 'Art gallery, bookshop, theatre. Check the calendar before going.',
    tags: ['gallery', 'art', 'victoria-island'],
  },
  {
    ...base('c-oaxaca-1', 0),
    title: 'Criollo',
    category: 'Eat',
    city: 'Oaxaca',
    country: 'Mexico',
    sourceUrl: 'https://www.criollo.mx',
    thumbnailUrl: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=1400&q=80',
    notes: 'Enrique Olvera’s Oaxaca project. One seating, one menu.',
    tags: ['tasting-menu', 'mexican', 'dinner'],
  },
  {
    ...base('c-porto-1', 0),
    title: 'The Yeatman',
    category: 'Stay',
    city: 'Porto',
    country: 'Portugal',
    sourceUrl: 'https://www.the-yeatman-hotel.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1400&q=80',
    notes: 'Across the river from Porto. Cellar tastings, long views of the Douro.',
    tags: ['boutique', 'wine', 'douro'],
  },
  {
    ...base('c-tokyo-1', 0),
    title: 'Toraya Akasaka',
    category: 'Eat',
    city: 'Tokyo',
    country: 'Japan',
    sourceUrl: 'https://www.toraya-group.co.jp',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=1400&q=80',
    notes: 'Wagashi house since 1526. Basement tea room is the move.',
    tags: ['tea', 'kissaten', 'historic'],
  },
];
